version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    # image: lscr.io/linuxserver/plex:1.32.6
    container_name: Plex
    network_mode: host
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - VERSION=docker
      # - VERSION=public
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      # - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
        - 32400:32400
        - 3005:3005
        - 8324:8324
        - 32469:32469
        - 1900:1900/udp
        - 5353:5353/udp
        - 32410:32410/udp
        - 32412:32412/udp
        - 32413:32413/udp
        - 32414:32414/udp
    volumes:
      - ../app/plex/config:/config
      - ../app/plex/transcode:/transcode
      - /mnt/pool1/pliki/plex:/data
    # devices:
    #   - /dev/nvidia0
    #   - /dev/nvidiactl
    #   - /dev/nvidia-uvm
    restart: unless-stopped

  kitana:
    image: pannal/kitana:latest
    container_name: Kitana
    volumes:
      - ../app/kitana/data:/app/data
    ports:
      - 31337:31337
    command: -B 0.0.0.0:31337 -P
    restart: unless-stopped